
#ifndef __ARCH_ARM_MACH_MSM_BOARD_EVE_H
#define __ARCH_ARM_MACH_MSM_BOARD_EVE_H

#define MSM_SMI_BASE        0x00100000
#define MSM_SMI_SIZE        0x00800000

#define MSM_PMEM_GPU0_BASE  MSM_SMI_BASE
#define MSM_PMEM_GPU0_SIZE  (7*SZ_1M)

//#define MSM_PMEM_GPU0_BASE      (0x10000000 + 64*SZ_1M)
//#define MSM_PMEM_GPU0_SIZE      0x800000

#define MSM_EBI_BASE            0x10000000
#define MSM_EBI_SIZE            0x06E00000

#define MSM_FB_BASE               (MSM_PMEM_GPU0_BASE+MSM_PMEM_GPU0_SIZE)
#define MSM_FB_SIZE               (1*SZ_1M)

#define MSM_PMEM_MDP_BASE         (MSM_LINUX_BASE + MSM_LINUX_SIZE)
#define MSM_PMEM_MDP_SIZE         (8*SZ_1M)

#define MSM_PMEM_ADSP_BASE        (MSM_PMEM_MDP_BASE + MSM_PMEM_MDP_SIZE)
#define MSM_PMEM_ADSP_SIZE        (13*SZ_1M)

#define MSM_PMEM_CAMERA_BASE      (MSM_PMEM_ADSP_BASE + MSM_PMEM_ADSP_SIZE)
#define MSM_PMEM_CAMERA_SIZE      (11*SZ_1M)

#define MSM_PMEM_GPU1_BASE        (MSM_PMEM_CAMERA_BASE + MSM_PMEM_CAMERA_SIZE)
#define MSM_PMEM_GPU1_SIZE        (8*SZ_1M)

#define MSM_LINUX_BASE            MSM_EBI_BASE
#define MSM_LINUX_SIZE            (223*SZ_1M - MSM_PMEM_MDP_SIZE-MSM_PMEM_ADSP_SIZE-MSM_PMEM_CAMERA_SIZE-MSM_PMEM_GPU1_SIZE)

#define MSM_RAM_CONSOLE_BASE      (MSM_PMEM_GPU1_SIZE+MSM_PMEM_GPU1_BASE)
#define MSM_RAM_CONSOLE_SIZE      (128 * SZ_1K)

/* panel */
#define GPIO_LCD_RESET_N			100
#define GPIO_LCD_VSYNC_O			97

#endif //__ARCH_ARM_MACH_MSM_BOARD_EVE_H
