CFLAGS_REMOVE_mt9p012_fox.o = -Werror
CFLAGS_REMOVE_mt9t013.o = -Werror
CFLAGS_REMOVE_mt9d112.o = -Werror
CFLAGS_REMOVE_s5k3e2fx.o = -Werror
CFLAGS_REMOVE_msm_camera.o = -Werror

# LGE_CHANGE [dojip.kim@lge.com] 2010-04-02, update for 2.6.29
# LGE_CHANGE_S [zugwan@lge.com] 2009-05-06
#obj-$(CONFIG_MSM_CAMERA) += msm_camera_probe.o msm_camera.o mt9p012_fox.o mt9p012_reg.o mt9t013.o mt9t013_reg.o mt9d112.o mt9d112_reg.o s5k3e2fx.o flash.o
obj-$(CONFIG_MSM_CAMERA) += msm_camera_probe.o msm_camera.o mv9319.o flash.o eve_flash_led.o
# LGE_CHANGE_E [zugwan@lge.com] 2009-05-06
obj-$(CONFIG_ARCH_MSM) += msm_vfe7x.o msm_io7x.o
obj-$(CONFIG_ARCH_QSD) += msm_vfe8x.o msm_vfe8x_proc.o msm_io8x.o 
